// pages/pathfinder.vue
<script setup lang="ts">
const store = useTrackerStore()

const startArea = ref('')
const endArea = ref('')

// Get all discovered areas from entrances
const accessibleAreas = computed(() => {
  const areas = new Set<string>()

  // Add all fromArea
  store.entrances.forEach(e => {
    if (e.fromArea) areas.add(e.fromArea)
  })

  // Add toArea from discovered entrances
  store.entrances.forEach(e => {
    if (e.to && e.toArea) {
      areas.add(e.toArea)
    }
  })

  return Array.from(areas).sort()
})

const findPath = () => {
  if (!startArea.value || !endArea.value) return
  // TODO: Implement pathfinding algorithm
  console.log('Finding path from', startArea.value, 'to', endArea.value)
}
</script>

<template>
  <UContainer>
    <div class="py-8">
      <UCard>
        <div class="space-y-6">
          <p class="text-gray-600 dark:text-gray-400">
            Find a route between two areas using your discovered entrances
          </p>

          <!-- Start/End Area Selectors -->
          <div class="grid grid-cols-2 gap-4">
            <USelectMenu
              v-model="startArea"
              :options="accessibleAreas"
              placeholder="Select start area..."
              searchable
              size="lg"
            />

            <USelectMenu
              v-model="endArea"
              :options="accessibleAreas"
              placeholder="Select end area..."
              searchable
              size="lg"
            />
          </div>

          <UButton
            size="xl"
            :disabled="!startArea || !endArea"
            @click="findPath"
          >
            Find Path
          </UButton>

          <!-- Accessible Areas Display -->
          <div class="mt-8">
            <p class="text-sm text-gray-600 dark:text-gray-400 mb-4">
              {{ accessibleAreas.length }} areas are accessible based on your discovered entrances
            </p>

            <div class="flex flex-wrap gap-2">
              <UBadge
                v-for="area in accessibleAreas"
                :key="area"
                variant="soft"
                size="lg"
              >
                {{ area }}
              </UBadge>
            </div>
          </div>
        </div>
      </UCard>
    </div>
  </UContainer>
</template>

// src/components/Pathfinder.tsx
import { useState, useMemo } from 'react';
import { useTrackerStore } from '../store/trackerStore';
import { REGIONS } from '../data/constants';
import type { Entrance } from '../types';

interface PathStep {
  from: string;
  to: string;
  entrance: string;
  destination: string;
  type: string;
}

export function Pathfinder() {
  const entrances = useTrackerStore((state) => state.entrances);
  const [startArea, setStartArea] = useState<string>('');
  const [endArea, setEndArea] = useState<string>('');
  const [path, setPath] = useState<PathStep[] | null>(null);
  const [error, setError] = useState<string>('');

  // Build a graph of connections from entrances that have been filled
  const graph = useMemo(() => {
    const connections: Map<string, Array<{ to: string; entrance: Entrance }>> = new Map();

    // Only include entrances where the destination has been filled
    const filledEntrances = entrances.filter(e => e.to && e.to.trim() !== '' && e.toArea && e.toArea.trim() !== '');

    for (const entrance of filledEntrances) {
      const from = entrance.fromArea;
      const to = entrance.toArea;

      if (!from || !to || from === 'Unknown' || to === 'Unknown' || from === 'Warp') continue;

      // Add forward connection
      if (!connections.has(from)) {
        connections.set(from, []);
      }
      connections.get(from)!.push({ to, entrance });

      // For bidirectional connections (not one-way), add reverse
      // Most entrances are bidirectional
      if (entrance.type === 'Overworld' || entrance.type === 'Grotto' ||
          entrance.type === 'Dungeon' || entrance.type === 'Interior' ||
          entrance.type === 'Hideout') {
        if (!connections.has(to)) {
          connections.set(to, []);
        }
        connections.get(to)!.push({ to: from, entrance });
      }
    }

    return connections;
  }, [entrances]);

  // BFS pathfinding algorithm
  const findPath = () => {
    setError('');
    setPath(null);

    if (!startArea || !endArea) {
      setError('Please select both start and end areas');
      return;
    }

    if (startArea === endArea) {
      setError('Start and end areas are the same');
      return;
    }

    // BFS to find shortest path
    const queue: Array<{ area: string; path: PathStep[] }> = [{ area: startArea, path: [] }];
    const visited = new Set<string>([startArea]);

    while (queue.length > 0) {
      const { area, path: currentPath } = queue.shift()!;

      // Check all connections from current area
      const connections = graph.get(area) || [];
      for (const { to, entrance } of connections) {
        if (visited.has(to)) continue;

        const newPath = [
          ...currentPath,
          {
            from: area,
            to,
            entrance: entrance.from,
            destination: entrance.to,
            type: entrance.type,
          },
        ];

        if (to === endArea) {
          // Found the path!
          setPath(newPath);
          return;
        }

        visited.add(to);
        queue.push({ area: to, path: newPath });
      }
    }

    setError('No path found. Make sure you have filled in the entrances connecting these areas.');
  };

  const availableAreas = useMemo(() => {
    return Array.from(graph.keys()).sort();
  }, [graph]);

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow">
        <h2 className="text-xl font-bold mb-2">Pathfinder</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400">
          Find a route between two areas using your discovered entrances
        </p>
      </div>

      {/* Input Section */}
      <div className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium mb-2">Start Area</label>
            <select
              value={startArea}
              onChange={(e) => setStartArea(e.target.value)}
              className="input-field w-full"
            >
              <option value="">Select start area...</option>
              {REGIONS.map((region) => (
                <option key={region} value={region}>
                  {region}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium mb-2">End Area</label>
            <select
              value={endArea}
              onChange={(e) => setEndArea(e.target.value)}
              className="input-field w-full"
            >
              <option value="">Select end area...</option>
              {REGIONS.map((region) => (
                <option key={region} value={region}>
                  {region}
                </option>
              ))}
            </select>
          </div>
        </div>

        <button
          onClick={findPath}
          className="btn-primary w-full md:w-auto"
          disabled={!startArea || !endArea}
        >
          Find Path
        </button>

        {error && (
          <div className="p-4 bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200 rounded">
            {error}
          </div>
        )}
      </div>

      {/* Results Section */}
      {path && (
        <div className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow">
          <h3 className="text-lg font-bold mb-4">
            Path from {startArea} to {endArea} ({path.length} step{path.length !== 1 ? 's' : ''})
          </h3>

          <div className="space-y-2">
            {path.map((step, index) => (
              <div
                key={index}
                className="p-3 bg-gray-50 dark:bg-gray-700 rounded-lg border-l-4 border-blue-500"
              >
                <div className="flex items-center gap-2">
                  <span className="text-sm font-bold text-gray-500 dark:text-gray-400">
                    {index + 1}.
                  </span>
                  <span className="font-medium text-blue-600 dark:text-blue-400">
                    {step.from}
                  </span>
                  <span className="text-gray-400">→</span>
                  <span className="font-medium text-green-600 dark:text-green-400">
                    {step.to}
                  </span>
                </div>
                <div className="ml-6 mt-1 text-sm text-gray-600 dark:text-gray-300">
                  <div className="flex flex-col gap-1">
                    <div>
                      <span className="text-xs text-gray-500 dark:text-gray-400">Use entrance: </span>
                      <span className="font-mono">{step.entrance}</span>
                    </div>
                    <div>
                      <span className="text-xs text-gray-500 dark:text-gray-400">Leads to: </span>
                      <span className="font-mono text-green-700 dark:text-green-300">{step.destination}</span>
                      <span className="ml-2 text-xs px-2 py-1 rounded bg-gray-200 dark:bg-gray-600">
                        {step.type}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Stats Section */}
      <div className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow">
        <h3 className="text-lg font-bold mb-2">Available Areas</h3>
        <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
          {availableAreas.length} areas are accessible based on your discovered entrances
        </p>
        <div className="flex flex-wrap gap-2">
          {availableAreas.map((area) => (
            <span
              key={area}
              className="px-3 py-1 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 rounded-full text-sm"
            >
              {area}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
